### PR TITLE
Make all entity keys available as route parameters

### LINKED ISSUE #14: Fast route with two placeholders
Already opened a similar discussion on https://discourse.laminas.dev/t/fast-route-with-two-placeholders/1403

Solution would be:

RouteBasedResourceStrategy.php

```
if (isset($data[$resourceIdentifier])) {
    $routeParams[$routeIdentifier] = $data[$resourceIdentifier];
}

// Auto inject all entity keys in route params
foreach($data as $key => $value) {
    $routeParams[$key] = $value;
}
```

### PR DESCRIPTION
**Pull request by arstom**
If you have more than one place holder in your route, this fix will automatically replace the other place holders, too.

Signed-off-by: arstom <spambar@web.de>

On branch route-fix
 Changes to be committed:
	modified:   src/ResourceGenerator/RouteBasedResourceStrategy.php

### CODE REVIEW

**Comment by weierophinney** [comment]
Does this replace #15?

**Comment by arstom** [comment]
Yes, this will replace #15 . Can you delete it? I was not able to do the needed steps for DCO in my first pull request.

**Comment by weierophinney** [comment]
Please have a look at the build results, as they indicate your patch is introducing a BC break:

- https://travis-ci.com/github/mezzio/mezzio-hal/jobs/375379651

**Comment by arstom** [comment]
> Please have a look at the build results, as they indicate your patch is introducing a BC break:
> 
> * https://travis-ci.com/github/mezzio/mezzio-hal/jobs/375379651

Errors haven been corrected

**Comment by arstom** [comment]
What can I do that Travis CI builds will go green?

**Comment by samsonasik** [comment]
you need to update unit tests, you can check the test error at https://travis-ci.com/github/mezzio/mezzio-hal/jobs/375446540#L485 .

You can run unit tests locally first before push , please read https://github.com/laminas/.github/blob/master/CONTRIBUTING.md#running-tests

**Comment by arstom** [comment]
I tried a lot but I cannot fix the unit test issue. In that case some knowledge is missing why my suggested fix results in a failed unit test.

**Pull request merged**
