### PR TITLE
Keep original query filters in route-based collection page `_links`

### PR DESCRIPTION
**Pull request by pauci**
Signed-off-by: Pavol Kirschbaum <pkirschbaum@sygic.com>

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Description

Keep original query filters in route-based paginated-collection page _links. Original query filters are already preserved in links generated for url-based collection and non-paginated route-based collection.

### CODE REVIEW

**Comment by hydrapolic** [comment]
friendly ping @Ocramius :)

**Comment by Ocramius** [comment]
Marked as BC Break tentatively, due to changed tests

**Comment by weierophinney** [comment]
The test changes make sense to me, and do not feel like a BC break.

Previously, we were not calling `getQueryParams()`, and instead just testing that if query param metadata was present in the collection that it was injected. With the proposed changes, `getQueryParams()` is called when producing a collection representation in order to get the initial query parameter set. The tests then demonstrate that the metadata is merged into that set.

Considering that the HAL specification details exactly this, I think of this as an improvement in our library, as we were not doing it previously.

The potential BC break is if this behavior is unwanted by a consumer; i.e., they NEVER want query string parameters passed in the request represented in the links. Currently, we clearly do not have a way to _disable_ it, and I'm wondering if we should. My inclination is that we add a constructor to the `RouteBasedCollectionStrategy` to allow disabling the functionality (but have it enabled by default). This would then also require:

- a factory for `RouteBasedCollectionStrategy`
- and a configuration key that the above factory can use to determine what to pass to the constructor

Another thing to consider: in the HAL support for laminas-api-tools, I _believe_ we had the ability to provide an allow-list of query string parameters from the request that could be merged into generated links. This might be an approach to consider as well; if so, we'd have a similar strategy to what I outlined above.

@Ocramius thoughts?

**Comment by Ocramius** [comment]
@weierophinney yeah, basically wondering about the "I never want query parameters" part. I don't think it's a major issue until somebody calls for it (which may never happen), but since you are happy with the patch as-is, let's roll with it :)

**Review by Ocramius — APPROVED** [review]
Thanks @pauci!

**Comment by hydrapolic** [comment]
Thanks @Ocramius @weierophinney @pauci !

**Pull request merged**
