### PR TITLE
Remove zendframework-bridge

### PR DESCRIPTION
**Pull request by tobias-trozowski**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Description
removed old zendframework bridge

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
@tobias-trozowski rebased this - some failures reported by `vimeo/psalm`:

```

Error: Class or interface Zend\Expressive\Hal\LinkGenerator\UrlGeneratorInterface does not exist
Error: Class or interface Zend\Expressive\Hal\HalResponseFactory does not exist
Error: Class or interface Zend\Expressive\Hal\LinkGenerator does not exist
Error: Class or interface Zend\Expressive\Hal\LinkGenerator\ExpressiveUrlGenerator does not exist
Error: Class or interface Zend\Expressive\Hal\Metadata\MetadataMap does not exist
Error: Class or interface Zend\Expressive\Hal\ResourceGenerator does not exist
Error: Class or interface Zend\Expressive\Hal\Renderer\JsonRenderer does not exist
Error: Argument 1 of Psr\Container\ContainerInterface::has cannot be mixed, expecting string
Error: Class or interface Zend\Expressive\Hal\Renderer\JsonRenderer does not exist
Error: Argument 1 of Psr\Container\ContainerInterface::get cannot be mixed, expecting string
Error: Class or interface Zend\Expressive\Hal\Renderer\XmlRenderer does not exist
Error: Argument 1 of Psr\Container\ContainerInterface::has cannot be mixed, expecting string
Error: Class or interface Zend\Expressive\Hal\Renderer\XmlRenderer does not exist
Error: Argument 1 of Psr\Container\ContainerInterface::get cannot be mixed, expecting string
Error: Class or interface Zend\Expressive\Helper\ServerUrlHelper does not exist
Error: Argument 1 of Psr\Container\ContainerInterface::has cannot be mixed, expecting string
Error: Class or interface Zend\Expressive\Helper\ServerUrlHelper does not exist
Error: Argument 1 of Psr\Container\ContainerInterface::get cannot be mixed, expecting string
Error: Class or interface Zend\Expressive\Hal\Renderer\JsonRenderer does not exist
Error: Class or interface Zend\Expressive\Hal\Renderer\XmlRenderer does not exist
Error: Class or interface Zend\Expressive\Helper\UrlHelper does not exist
Error: Class or interface Zend\Expressive\Helper\UrlHelper does not exist
Error: Class or interface Zend\Expressive\Helper\ServerUrlHelper does not exist
Error: Class or interface Zend\Expressive\Helper\ServerUrlHelper does not exist
Error: Class or interface Zend\Expressive\Helper\ServerUrlHelper does not exist
Error: Class or interface Zend\Expressive\Helper\ServerUrlHelper does not exist
```

**Comment by tobias-trozowski** [comment]
i'm thinking about removing the old zend aliases we are still using too.
IMO we remove any support for zend with removal of the bridge.
any opinions on this?

**Comment by Ocramius** [comment]
> i'm thinking about removing the old zend aliases we are still using too.

We can't: those are strings that can be referenced downstream. Can be done in a major version.

**Review by Ocramius — APPROVED** [review]
LGTM! :+1: 

Thanks @tobias-trozowski!

**Comment by cronlabspl** [comment]
> > i'm thinking about removing the old zend aliases we are still using too.
> 
> We can't: those are strings that can be referenced downstream. Can be done in a major version.

Oh yes; you can ( and should )

**Comment by Ocramius** [comment]
@cronlabspl not until a new major.

**Comment by cronlabspl** [comment]
> @cronlabspl not until a new major.

Why not? Serious question

**Comment by tobias-trozowski** [comment]
> > @cronlabspl not until a new major.
> 
> Why not? Serious question. Whats wrong with adding new features to `minor`?

new feature in minor is ok, but this would be a feature removal.
**removing** the `Zend\Expressive\Hal\*` from config and code etc. would break downstream packages which still use these identifiers

**Pull request merged**
