### PR TITLE
PSR-17 support

### PR DESCRIPTION
**Pull request by tobias-trozowski**
|    Q          |   A
|-------------- | ------
| BC Break      | no
| New Feature   | yes

### Description
Based on @boesing's work from his [PSR-17 support #43](https://github.com/mezzio/mezzio-hal/pull/43) PR.

This PR is going to provide an integration with [PSR-17: HTTP Factories](https://www.php-fig.org/psr/psr-17/).

### CODE REVIEW

**Comment by froschdesign** [comment]
> This PR is going to provide an integration with [PSR-17: HTTP Factories](https://www.php-fig.org/psr/psr-17/).

This also means that the documentation must be updated and the readme file, repository description, etc. This also has a _promotional character_ when we can say that this package supports various PSR standards.

**Comment by weierophinney** [comment]
@tobias-trozowski Can you rebase from #43, please? I've provided a number of changes there since rebasing, and I'd like to get an idea how much the two of these patches differ.

What is the key difference with your patch, versus the one submitted by @boesing?

**Comment by boesing** [comment]
@weierophinney I actually don't have time to work on this and thus I suggested to use my initial work as a base for further enhancements regarding public methods which are marked `internal`.

**Comment by tobias-trozowski** [comment]
@weierophinney i removed the getters which were only used to assert them in tests. already rebased against `2.3.x`.

**Comment by weierophinney** [comment]
I've rebased to pick up the bump to PHP 7.4, and the additional Psalm fixes I performed yesterday. I'll get documentation updated in a few hours so this can be completed.

**Comment by weierophinney** [comment]
@froschdesign I'll give you a chance to review the documentation changes before I merge. They're primarily in:

- README.md
- docs/book/index.md
- docs/book/v2/factories.md

(The other doc changes were due to linting errors; I didn't want to create a new PR to fix those and have to rebase this one again.)

**Review by froschdesign — APPROVED** [review]

**Pull request merged**
